# # # # # # # # # # # # #
#   K i k o - p l u s   #
# # # # # # # # # # # # #

# Basic
name:               "wjjwkwindy"



author:
  name:             wjjwkwindy
  github:           wjjwkwindy
  twitter:          619118498
  email:            wjjwkwindy|gmail.com

# Google-analytics
google-analytics:
  #id:               "UA-86298174-1"

# Baidu-analytics
baidu-analytics:
  id:               true

# Disqus
disqus:
  id:               "wjjwkwindy"

# URL
url:                "http://wjjwkwindy.com"
#url:               "http://127.0.0.1:4000"
baseurl:            ""


# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:           Asia/Shang_Hai
permalink:          /:year-:month-:day/:title/

# Pagination
paginate:           5
paginate_path:      /page:num/

# Markdown
markdown:           kramdown
kramdown:
  imput:            GFM

# Navigation
nav:
  - name:           "About"
    url:            "/about"
    target:         "_top"

  - name:           "Archive"
    url:            "/archive"
    target:         "_top"

  - name:           "Tags"
    url:            "/tags"
    target:         "_top"

  - name:           "Github"
    url:            "https://github.com/wjjwkwindy"
    target:         "_blank"



# Sass
sass:
  sass_dir:         _sass
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

# jekyll-seo-tag, see: http://www.rubydoc.info/gems/jekyll-seo-tag/1.2.0
gems:
  - jekyll-seo-tag
  - jekyll-paginate

exclude:            [vendor]
